//! Apache Fory binary transport for [`tarpc`](https://docs.rs/tarpc).
//!
//! Re-exports the fory transport from `tarpc::serde_transport::fory` plus
//! the wrapper envelope types from `tarpc::serde_transport::fory_envelope`,
//! letting you depend on a single stable crate name without manually pinning
//! a fork branch or flipping feature flags on tarpc directly.
//!
//! # Status
//!
//! Wire codec, wrapper envelopes, lower-level transport API, and the canonical
//! `#[tarpc::service]` proc-macro flow all work and are tested. Envelope types
//! use hand-written `fory::Serializer` impls registered via
//! `fory.register_serializer(id)` (EXT path), which sidesteps the fory-derive
//! `TYPE_ID_COUNTER` collision with user-derived types. User types use
//! `#[derive(fory::ForyObject)]` normally — no per-type rewrite required.
//!
//! See README.md for the full guide and a `#[tarpc::service]` example.
//!
//! # Quick start
//!
//! ```ignore
//! use fory::Fory;
//! use std::sync::Arc;
//!
//! let mut fory = Fory::default();
//! // Use register_envelope_types to register all envelope types at once.
//! // This registers via register_serializer (EXT type path) which avoids the
//! // fory-derive TYPE_ID_COUNTER collision between independently compiled crates.
//! tarpc_fory::register_envelope_types::<String>(&mut fory).unwrap();
//! let fory = Arc::new(fory);
//!
//! # async fn ex(addr: std::net::SocketAddr) -> std::io::Result<()> {
//! let transport = tarpc_fory::connect::<_, String, String>(addr, fory).await?;
//! # Ok(()) }
//! ```
//!
//! See the [README](https://github.com/justinholmes/tarpc-fory) for the
//! full guide including limitations.

pub use tarpc::serde_transport::fory::{
    connect, connect_with_fory, listen, listen_with_fory, Incoming, ForyEnvelopeCodec,
};
pub use tarpc::serde_transport::fory_envelope::{
    fory_wire_id, register_envelope_types, ForyClientMessage, ForyRequest, ForyResponse,
    ForyServerError, ForyTraceContext, ServiceWireSchema,
};
pub use tokio_serde_fory::ForyCodec;

/// Envelope types used for fory transport.
///
/// Re-exports the fory-serializable wrapper types for tarpc envelope messages.
/// Referenced by code generated by `#[tarpc_fory::fory_service]`.
pub mod envelope {
    pub use tarpc::serde_transport::fory_envelope::{
        ForyClientMessage, ForyRequest, ForyResponse, ForyServerError, ForyTraceContext,
        ServiceWireSchema, fory_wire_id, register_envelope_types,
    };
}
